### ISSUE TITLE
Some type parameters can be removed in implicit defs

### ISSUE THREAD

**Issue by etorreborre** [ProjectSeptemberInc/freek#11]
@mandubian I was reading the code and I realized that some type parameters can be removed like `C` [here](https://github.com/ProjectSeptemberInc/freek/blob/27164ec3921410714755f14ccf757e1b5e438671/src/main/scala/CoproductK.scala#L315).

**Comment by mandubian** [comment]
oh yes thanks!
Copypasting implicit proofs :)
Don't hesitate to tell if you see improvements, the code is still a bit messy as I keep older cases not to forget them when I do evolutions

**Comment by etorreborre** [comment]
I suppose this is fixed now so I'm closing this.
