### ISSUE TITLE
StateT

### ISSUE THREAD

**Issue by dispalt** [ProjectSeptemberInc/freek#13]
I was looking at this [project](https://github.com/aeyakovenko/mesos-edsl) and wondering how it would change if I were to use freek.  I am fairly new to most of this more intense monadic stuff, but have been scratching my head for a few days as I try to slog through connecting one to the other.  I guess the biggest difference is the use of StateT, but I am probably way in over my head, however, it is a real world problem I am looking to solve so I figured it would be a good opportunity to apply some of this stuff, if it makes sense.

So to my question, do you have any cursory tips on how to apply your clean division (freek) to this problem set?  Do you need more information?

**Comment by mandubian** [comment]
sorry I missed your message, github never notified me about it :)
Can you be more precise on the way they use Free monads there?
Free monads are monads that can be used with State monads too... but it depends on the way you want to use them...

**Comment by dispalt** [comment]
I forgot what this was about.
